version: "3.7"
services:
  mysql:
    image: mysql:8.0
    ports:
      - '4449:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

#  postgres:
#    image: postgres:12-alpine
#    ports:
#      - '5432:5432'
#    environment:
#      - POSTGRES_DB=db
#      - POSTGRES_USER=app
#      - POSTGRES_PASSWORD=pass